### ISSUE TITLE
Icon Not Found Causes studio to be unable to launch (my python install is scuffed also)

### ISSUE THREAD

**Issue by supercoolspy** [Bugadinho/Cork#1]
```
Traceback (most recent call last):
  File "/home/spy/.local/bin/cork", line 8, in <module>
    sys.exit(main())
  File "/home/spy/.local/lib/python3.10/site-packages/cork/__main__.py", line 171, in main
    this_splash.show("roblox-studio")
  File "/home/spy/.local/lib/python3.10/site-packages/cork/splash.py", line 78, in show
    self.gtk_splash = GtkCorkSplash(icon)
  File "/home/spy/.local/lib/python3.10/site-packages/cork/splash.py", line 26, in __init__
    Gtk.IconTheme.get_default().load_icon(icon, 112, 0))
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'roblox-studio' not present in theme Yaru (0)
```
https://github.com/Bugadinho/Cork/blob/8eb1a939dcf4014c8daaad94539be4aa2856bb5a/cork/splash.py#L78C33-L78C33 seems to cause the issue I'll try fixing it

**Comment by supercoolspy** [comment]
also for the player

**Comment by Bugadinho** [comment]
Just pushed an update, check it if helps out.

**Comment by Bugadinho** [comment]
Issue has been fixed with the previous update and the migration to Qt
