### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by n0signal1** [Bugadinho/Cork#8]
when i type "cork player" to launch it in the terminal, it does this:
(python3:3242): Gtk-WARNING **: 08:28:47.266: Theme parsing error: gtk.css:7661:22: 'shadow_4' is not a valid color name
Traceback (most recent call last):
  File "/usr/local/bin/cork", line 33, in <module>
    sys.exit(load_entry_point('cork-launcher==1.0.0', 'console_scripts', 'cork')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cork/__main__.py", line 209, in main
    process = session.execute_player(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cork/bootstrapper/session.py", line 96, in execute_player
    player_exe, player_directory = self.get_player(
                                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cork/bootstrapper/session.py", line 29, in get_player
    version = version_override if version_override != "" else client_version.get(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cork/roblox/version.py", line 10, in get
    version_response = request.urlopen(request.Request(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by n0signal1** [comment]
and it also gets stuck on "getting version"

**Comment by Bugadinho** [comment]
That sounds like a connection error to the clientsettings url, perhaps try updating to the latest version which had a change surrounding that.
